"""
Dental RAG Module
==================
Retrieval-Augmented Generation for dental clinical guidelines and treatment planning.

Based on: Medical-RAG-LLM - Enhanced for dental domain
"""

import os
import json
from pathlib import Path
from typing import Optional, List, Dict, Any, Union
from dataclasses import dataclass, asdict
from enum import Enum

try:
    from langchain.text_splitter import RecursiveCharacterTextSplitter
    from langchain_community.vectorstores import Chroma
    from langchain_community.embeddings import HuggingFaceEmbeddings
    from langchain.schema import Document
    LANGCHAIN_AVAILABLE = True
except ImportError:
    LANGCHAIN_AVAILABLE = False
    print("Warning: langchain not installed. RAG features will be limited.")


class TreatmentCategory(str, Enum):
    """Categories of dental treatments."""
    PREVENTIVE = "Preventive"
    RESTORATIVE = "Restorative"
    ENDODONTIC = "Endodontic"
    PERIODONTIC = "Periodontic"
    PROSTHODONTIC = "Prosthodontic"
    ORAL_SURGERY = "Oral Surgery"
    ORTHODONTIC = "Orthodontic"
    PEDIATRIC = "Pediatric"


@dataclass
class TreatmentOption:
    """Represents a treatment option with details."""
    name: str
    category: str
    description: str
    indications: List[str]
    contraindications: List[str]
    procedure_steps: List[str]
    estimated_cost_range: Dict[str, float]  # {"min": x, "max": y, "currency": "AED"}
    recovery_time: str
    success_rate: float  # 0-100
    references: List[str]
    
    def to_dict(self) -> Dict[str, Any]:
        return asdict(self)


@dataclass
class TreatmentPlan:
    """Complete treatment plan generated by RAG."""
    condition: str
    severity: str
    primary_treatment: TreatmentOption
    alternative_treatments: List[TreatmentOption]
    follow_up_recommendations: List[str]
    prognosis: str
    guidelines_sources: List[str]
    confidence_score: float
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            "condition": self.condition,
            "severity": self.severity,
            "primary_treatment": self.primary_treatment.to_dict(),
            "alternative_treatments": [t.to_dict() for t in self.alternative_treatments],
            "follow_up_recommendations": self.follow_up_recommendations,
            "prognosis": self.prognosis,
            "guidelines_sources": self.guidelines_sources,
            "confidence_score": self.confidence_score
        }


class DentalGuidelinesRAG:
    """
    RAG system for dental clinical guidelines and treatment planning.
    
    Features:
    - Vector store for clinical guidelines
    - Treatment recommendation based on conditions
    - Cost estimation for Dubai market
    - Multi-source guideline retrieval (ADA, WHO, local)
    """
    
    # Embedded dental guidelines knowledge base
    DENTAL_GUIDELINES = [
        # Caries Treatment Guidelines
        {
            "condition": "Caries",
            "severity": "mild",
            "content": """
            DENTAL CARIES TREATMENT GUIDELINES - MILD SEVERITY
            
            Source: American Dental Association (ADA) Clinical Practice Guidelines
            
            INDICATION: Early enamel caries, white spot lesions, incipient decay
            
            RECOMMENDED TREATMENTS:
            1. Fluoride Varnish Application
               - Apply 5% sodium fluoride varnish
               - Repeat every 3-6 months
               - Cost: AED 150-300
            
            2. Dental Sealants (for pits/fissures)
               - Apply resin-based sealant
               - Monitor at regular visits
               - Cost: AED 200-400 per tooth
            
            3. Remineralization Therapy
               - Calcium phosphate products (MI Paste)
               - High-fluoride toothpaste (5000 ppm)
               
            MONITORING: Re-evaluate in 3-6 months
            SUCCESS RATE: 85-95% with early intervention
            """,
            "category": TreatmentCategory.PREVENTIVE.value
        },
        {
            "condition": "Caries",
            "severity": "moderate",
            "content": """
            DENTAL CARIES TREATMENT GUIDELINES - MODERATE SEVERITY
            
            Source: ADA & FDI World Dental Federation Guidelines
            
            INDICATION: Dentin caries, cavitated lesions not approaching pulp
            
            RECOMMENDED TREATMENTS:
            1. Direct Composite Restoration
               - Remove caries with high-speed handpiece
               - Etch, bond, place composite resin
               - Polish and adjust occlusion
               - Cost: AED 400-800 per surface
            
            2. Glass Ionomer Restoration (alternative)
               - Indicated for cervical lesions
               - Fluoride-releasing properties
               - Cost: AED 300-600
            
            PROCEDURE:
            - Local anesthesia if needed
            - Rubber dam isolation
            - Caries excavation (complete removal)
            - Liner if deep (calcium hydroxide)
            - Bonding and restoration
            
            FOLLOW-UP: 6 months, bitewing radiograph at 12 months
            SUCCESS RATE: 90-95% at 5 years
            """,
            "category": TreatmentCategory.RESTORATIVE.value
        },
        {
            "condition": "Deep Caries",
            "severity": "severe",
            "content": """
            DEEP CARIES TREATMENT GUIDELINES - APPROACHING PULP
            
            Source: American Association of Endodontists (AAE) Guidelines
            
            INDICATION: Caries extending into deep dentin, proximity to pulp
            
            TREATMENT OPTIONS:
            1. Stepwise Caries Removal (preferred for vital teeth)
               - First visit: Remove peripheral caries, leave affected dentin over pulp
               - Place calcium hydroxide or MTA
               - Temporary restoration
               - Re-entry in 6-8 weeks for complete excavation
               - Cost: AED 800-1500
            
            2. Direct Pulp Capping (if exposure occurs)
               - Indicated for small mechanical exposure
               - MTA or Biodentine placement
               - Monitor vitality
               - Cost: AED 600-1000
            
            3. Indirect Pulp Capping
               - Leave small amount of affected dentin
               - Calcium hydroxide liner
               - Permanent restoration
               - Cost: AED 500-900
            
            WARNING SIGNS FOR ROOT CANAL:
            - Spontaneous pain
            - Prolonged cold sensitivity (>30 seconds)
            - Periapical radiolucency
            - Negative vitality testing
            
            SUCCESS RATE: 80-90% pulp preservation
            """,
            "category": TreatmentCategory.ENDODONTIC.value
        },
        {
            "condition": "Periapical Lesion",
            "severity": "critical",
            "content": """
            PERIAPICAL LESION TREATMENT GUIDELINES
            
            Source: AAE Endodontic Guidelines, European Society of Endodontology
            
            INDICATION: Periapical radiolucency, non-vital tooth, abscess
            
            URGENT TREATMENT REQUIRED
            
            TREATMENT OPTIONS:
            1. Non-Surgical Root Canal Therapy (First Line)
               - Complete chemomechanical debridement
               - Sodium hypochlorite irrigation (2.5-5.25%)
               - Calcium hydroxide inter-appointment medicament
               - Obturation with gutta-percha
               - Cost: AED 1500-3500 (anterior), AED 2500-5000 (molar)
            
            2. Surgical Endodontics (if non-surgical fails)
               - Apicoectomy with retrograde filling
               - Indicated after failed retreatment
               - Cost: AED 3000-6000
            
            3. Extraction (if non-restorable)
               - Consider implant replacement
               - Preserve bone with socket grafting
               - Cost: AED 500-1500 (extraction) + implant
            
            ACUTE ABSCESS MANAGEMENT:
            - Incision and drainage if fluctuant
            - Antibiotics if systemic involvement
            - Amoxicillin 500mg TID x 7 days (first line)
            - Clindamycin 300mg QID if penicillin allergy
            
            PROGNOSIS: 85-95% success with proper root canal
            FOLLOW-UP: Radiograph at 6 months, 12 months, then annually
            """,
            "category": TreatmentCategory.ENDODONTIC.value
        },
        {
            "condition": "Impacted Tooth",
            "severity": "moderate",
            "content": """
            IMPACTED TOOTH TREATMENT GUIDELINES
            
            Source: American Association of Oral and Maxillofacial Surgeons (AAOMS)
            
            INDICATION: Third molar impaction, supernumerary teeth, ectopic eruption
            
            CLASSIFICATION (Winter's):
            - Mesioangular: Most common, easiest extraction
            - Horizontal: Moderate difficulty
            - Vertical: Variable difficulty
            - Distoangular: Most difficult
            
            TREATMENT OPTIONS:
            1. Surgical Extraction
               - Indicated for symptomatic impaction
               - Pericoronitis episodes
               - Caries on adjacent tooth
               - Cyst formation
               - Cost: AED 1000-3000 per tooth
            
            2. Coronectomy (alternative for high-risk cases)
               - When root apex near inferior alveolar nerve
               - Remove crown, leave roots
               - Cost: AED 1500-2500
            
            3. Observation
               - Asymptomatic, fully impacted
               - Annual radiographic monitoring
            
            SURGICAL CONSIDERATIONS:
            - CBCT if close to nerve canal
            - Informed consent for nerve damage risk
            - Consider IV sedation or GA for multiple extractions
            
            POST-OPERATIVE CARE:
            - Ice packs 20 min on/off for 24-48 hours
            - Soft diet for 1 week
            - Chlorhexidine rinse starting day 2
            - Analgesics: Ibuprofen 400-600mg Q6H
            
            RECOVERY: 1-2 weeks full recovery
            SUCCESS RATE: 99% for routine extractions
            """,
            "category": TreatmentCategory.ORAL_SURGERY.value
        },
        {
            "condition": "Root Canal",
            "severity": "treatment",
            "content": """
            ROOT CANAL TREATMENT GUIDELINES
            
            Source: AAE Standards of Practice, ESE Quality Guidelines
            
            INDICATIONS:
            - Irreversible pulpitis
            - Pulp necrosis
            - Previously treated teeth requiring retreatment
            
            PROCEDURE STEPS:
            1. Diagnosis and treatment planning
               - Pulp vitality testing
               - Periapical radiograph
               - CBCT if complex anatomy
            
            2. Access cavity preparation
               - Straight-line access to canals
               - Locate all canal orifices
            
            3. Working length determination
               - Electronic apex locator
               - Radiographic confirmation
            
            4. Chemomechanical preparation
               - Crown-down technique
               - NiTi rotary instruments
               - Copious irrigation (NaOCl, EDTA)
            
            5. Obturation
               - Gutta-percha with sealer
               - Warm vertical compaction (gold standard)
            
            6. Coronal restoration
               - Core buildup
               - Full coverage crown recommended for posterior teeth
            
            COST BREAKDOWN (Dubai):
            - Anterior tooth: AED 1500-3000
            - Premolar: AED 2000-3500
            - Molar: AED 2500-5000
            - Retreatment: +50% additional
            - Crown: AED 2000-5000
            
            SUCCESS RATE: 90-95% primary treatment, 75-85% retreatment
            """,
            "category": TreatmentCategory.ENDODONTIC.value
        },
        {
            "condition": "Crown",
            "severity": "treatment",
            "content": """
            DENTAL CROWN GUIDELINES
            
            Source: ADA Council on Scientific Affairs
            
            INDICATIONS:
            - Extensive caries/restoration
            - Post-endodontic treatment (posterior teeth)
            - Fractured tooth
            - Cosmetic improvement
            
            CROWN TYPES:
            1. All-Ceramic (Zirconia/E.max)
               - Best aesthetics
               - Anterior and posterior use
               - Cost: AED 2500-5000
            
            2. Porcelain-Fused-to-Metal (PFM)
               - Good strength and aesthetics
               - Cost: AED 1500-3000
            
            3. Full Gold
               - Best longevity
               - Posterior teeth only
               - Cost: AED 3000-6000
            
            PREPARATION GUIDELINES:
            - Occlusal reduction: 1.5-2mm
            - Axial reduction: 1-1.5mm
            - Finish line: Chamfer or shoulder
            - Taper: 6-10 degrees
            
            CEMENTATION:
            - Conventional cement for metal-based
            - Adhesive cement for all-ceramic
            
            LONGEVITY: 10-15 years average with proper care
            """,
            "category": TreatmentCategory.PROSTHODONTIC.value
        },
        {
            "condition": "Bone Loss",
            "severity": "severe",
            "content": """
            PERIODONTAL BONE LOSS TREATMENT GUIDELINES
            
            Source: American Academy of Periodontology (AAP)
            
            CLASSIFICATION (2017 AAP/EFP):
            - Stage I: Initial periodontitis (1-2mm bone loss)
            - Stage II: Moderate periodontitis (3-4mm bone loss)
            - Stage III: Severe periodontitis (≥5mm bone loss)
            - Stage IV: Advanced periodontitis + tooth loss
            
            TREATMENT BY STAGE:
            
            Stage I-II:
            - Non-surgical periodontal therapy
            - Scaling and root planing
            - Local antimicrobials
            - Cost: AED 800-2000
            
            Stage III:
            - Surgical periodontal therapy
            - Open flap debridement
            - Regenerative procedures (bone grafting, GTR)
            - Cost: AED 3000-8000
            
            Stage IV:
            - Comprehensive treatment planning
            - Consider extractions and implants
            - Full mouth rehabilitation
            - Cost: AED 10,000-50,000+
            
            MAINTENANCE:
            - 3-month recall intervals
            - Supportive periodontal therapy
            - Home care reinforcement
            
            RISK FACTORS TO ADDRESS:
            - Smoking cessation (critical)
            - Diabetes control (HbA1c <7%)
            - Stress management
            
            PROGNOSIS: Variable, depends on compliance and risk factors
            """,
            "category": TreatmentCategory.PERIODONTIC.value
        }
    ]
    
    def __init__(
        self,
        embedding_model: str = "sentence-transformers/all-MiniLM-L6-v2",
        persist_directory: Optional[str] = None,
        collection_name: str = "dental_guidelines"
    ):
        """
        Initialize the Dental RAG system.
        
        Args:
            embedding_model: HuggingFace model for embeddings
            persist_directory: Directory to persist vector store
            collection_name: Name for the Chroma collection
        """
        self.embedding_model_name = embedding_model
        self.persist_directory = persist_directory
        self.collection_name = collection_name
        self.vectorstore: Optional[Chroma] = None
        self.embeddings = None
        
        if LANGCHAIN_AVAILABLE:
            self._initialize_embeddings()
            self._initialize_vectorstore()
    
    def _initialize_embeddings(self) -> None:
        """Initialize the embedding model."""
        self.embeddings = HuggingFaceEmbeddings(
            model_name=self.embedding_model_name,
            model_kwargs={'device': 'cpu'},
            encode_kwargs={'normalize_embeddings': True}
        )
    
    def _initialize_vectorstore(self) -> None:
        """Initialize and populate the vector store."""
        documents = []
        
        for guideline in self.DENTAL_GUIDELINES:
            doc = Document(
                page_content=guideline["content"],
                metadata={
                    "condition": guideline["condition"],
                    "severity": guideline["severity"],
                    "category": guideline["category"],
                    "source": "Dental AI Knowledge Base"
                }
            )
            documents.append(doc)
        
        # Split into smaller chunks for better retrieval
        text_splitter = RecursiveCharacterTextSplitter(
            chunk_size=1000,
            chunk_overlap=200,
            length_function=len,
        )
        splits = text_splitter.split_documents(documents)
        
        # Create vector store
        if self.persist_directory:
            self.vectorstore = Chroma.from_documents(
                documents=splits,
                embedding=self.embeddings,
                persist_directory=self.persist_directory,
                collection_name=self.collection_name
            )
        else:
            self.vectorstore = Chroma.from_documents(
                documents=splits,
                embedding=self.embeddings,
                collection_name=self.collection_name
            )
    
    def retrieve_guidelines(
        self,
        condition: str,
        severity: Optional[str] = None,
        k: int = 3
    ) -> List[Dict[str, Any]]:
        """
        Retrieve relevant clinical guidelines.
        
        Args:
            condition: Dental condition to search for
            severity: Optional severity level
            k: Number of results to return
            
        Returns:
            List of relevant guideline documents
        """
        if not LANGCHAIN_AVAILABLE or self.vectorstore is None:
            # Return from embedded knowledge if LangChain not available
            return self._fallback_retrieve(condition, severity)
        
        query = f"{condition} treatment guidelines"
        if severity:
            query += f" {severity} severity"
        
        results = self.vectorstore.similarity_search_with_score(query, k=k)
        
        retrieved = []
        for doc, score in results:
            retrieved.append({
                "content": doc.page_content,
                "metadata": doc.metadata,
                "relevance_score": round(1 - score, 4)  # Convert distance to similarity
            })
        
        return retrieved
    
    def _fallback_retrieve(
        self,
        condition: str,
        severity: Optional[str] = None
    ) -> List[Dict[str, Any]]:
        """Fallback retrieval without LangChain."""
        results = []
        condition_lower = condition.lower()
        
        for guideline in self.DENTAL_GUIDELINES:
            if condition_lower in guideline["condition"].lower():
                if severity is None or severity.lower() in guideline["severity"].lower():
                    results.append({
                        "content": guideline["content"],
                        "metadata": {
                            "condition": guideline["condition"],
                            "severity": guideline["severity"],
                            "category": guideline["category"]
                        },
                        "relevance_score": 0.9
                    })
        
        return results[:3]
    
    def generate_treatment_plan(
        self,
        condition: str,
        severity: str,
        patient_factors: Optional[Dict[str, Any]] = None
    ) -> TreatmentPlan:
        """
        Generate a comprehensive treatment plan.
        
        Args:
            condition: Detected dental condition
            severity: Severity level
            patient_factors: Optional patient-specific factors
            
        Returns:
            Complete TreatmentPlan with options
        """
        # Retrieve relevant guidelines
        guidelines = self.retrieve_guidelines(condition, severity)
        
        # Parse treatment options from guidelines
        primary_treatment, alternatives = self._parse_treatments(guidelines, condition, severity)
        
        # Generate follow-up recommendations
        follow_ups = self._generate_follow_ups(condition, severity)
        
        # Determine prognosis
        prognosis = self._assess_prognosis(condition, severity, guidelines)
        
        # Collect sources
        sources = list(set([
            g["metadata"].get("source", "Clinical Guidelines")
            for g in guidelines
        ]))
        
        # Calculate confidence based on retrieval scores
        confidence = sum([g["relevance_score"] for g in guidelines]) / max(len(guidelines), 1)
        
        return TreatmentPlan(
            condition=condition,
            severity=severity,
            primary_treatment=primary_treatment,
            alternative_treatments=alternatives,
            follow_up_recommendations=follow_ups,
            prognosis=prognosis,
            guidelines_sources=sources,
            confidence_score=round(confidence, 2)
        )
    
    def _parse_treatments(
        self,
        guidelines: List[Dict],
        condition: str,
        severity: str
    ) -> tuple[TreatmentOption, List[TreatmentOption]]:
        """Parse treatment options from retrieved guidelines."""
        
        # Default treatments based on condition
        treatment_map = {
            "Caries": {
                "mild": TreatmentOption(
                    name="Fluoride Therapy + Monitoring",
                    category=TreatmentCategory.PREVENTIVE.value,
                    description="Non-invasive remineralization therapy with professional fluoride application",
                    indications=["Early enamel caries", "White spot lesions", "Incipient decay"],
                    contraindications=["Cavitated lesions", "Dentin involvement"],
                    procedure_steps=[
                        "Professional cleaning",
                        "Apply 5% sodium fluoride varnish",
                        "Prescribe high-fluoride toothpaste",
                        "Dietary counseling"
                    ],
                    estimated_cost_range={"min": 150, "max": 400, "currency": "AED"},
                    recovery_time="None - immediate return to normal activities",
                    success_rate=90.0,
                    references=["ADA Clinical Practice Guidelines 2023"]
                ),
                "moderate": TreatmentOption(
                    name="Composite Resin Restoration",
                    category=TreatmentCategory.RESTORATIVE.value,
                    description="Direct tooth-colored filling to restore cavity",
                    indications=["Dentin caries", "Cavitated lesions", "Failed restorations"],
                    contraindications=["Pulp exposure", "Extensive destruction"],
                    procedure_steps=[
                        "Local anesthesia",
                        "Rubber dam isolation",
                        "Caries removal",
                        "Etch and bond",
                        "Composite placement and curing",
                        "Polish and adjust occlusion"
                    ],
                    estimated_cost_range={"min": 400, "max": 1000, "currency": "AED"},
                    recovery_time="1-2 hours post-anesthesia numbness",
                    success_rate=92.0,
                    references=["ADA Guidelines", "FDI World Dental Federation"]
                )
            },
            "Deep Caries": {
                "severe": TreatmentOption(
                    name="Stepwise Caries Excavation",
                    category=TreatmentCategory.ENDODONTIC.value,
                    description="Conservative two-stage caries removal to preserve pulp vitality",
                    indications=["Deep caries near pulp", "Vital tooth", "No spontaneous pain"],
                    contraindications=["Pulp necrosis", "Periapical pathology", "Spontaneous pain"],
                    procedure_steps=[
                        "First visit: Remove peripheral caries",
                        "Leave affected dentin over pulp",
                        "Apply calcium hydroxide/MTA",
                        "Temporary restoration",
                        "Second visit (6-8 weeks): Complete excavation",
                        "Permanent restoration"
                    ],
                    estimated_cost_range={"min": 800, "max": 1800, "currency": "AED"},
                    recovery_time="6-8 weeks between visits",
                    success_rate=85.0,
                    references=["AAE Guidelines", "ESE Position Statement"]
                )
            },
            "Periapical Lesion": {
                "critical": TreatmentOption(
                    name="Root Canal Therapy",
                    category=TreatmentCategory.ENDODONTIC.value,
                    description="Complete endodontic treatment to eliminate infection and preserve tooth",
                    indications=["Periapical radiolucency", "Non-vital tooth", "Dental abscess"],
                    contraindications=["Non-restorable tooth", "Vertical root fracture"],
                    procedure_steps=[
                        "Diagnosis and treatment planning",
                        "Local anesthesia and isolation",
                        "Access cavity preparation",
                        "Working length determination",
                        "Chemomechanical preparation",
                        "Calcium hydroxide medicament",
                        "Obturation with gutta-percha",
                        "Coronal restoration"
                    ],
                    estimated_cost_range={"min": 2000, "max": 5500, "currency": "AED"},
                    recovery_time="1-3 days post-operative discomfort",
                    success_rate=92.0,
                    references=["AAE Standards", "ESE Quality Guidelines"]
                )
            },
            "Impacted": {
                "moderate": TreatmentOption(
                    name="Surgical Extraction",
                    category=TreatmentCategory.ORAL_SURGERY.value,
                    description="Surgical removal of impacted tooth",
                    indications=["Symptomatic impaction", "Pericoronitis", "Adjacent tooth caries"],
                    contraindications=["Asymptomatic fully impacted", "High surgical risk"],
                    procedure_steps=[
                        "CBCT imaging if indicated",
                        "Local anesthesia (or sedation)",
                        "Mucoperiosteal flap",
                        "Bone removal if needed",
                        "Tooth sectioning",
                        "Extraction",
                        "Socket debridement",
                        "Suturing"
                    ],
                    estimated_cost_range={"min": 1200, "max": 3500, "currency": "AED"},
                    recovery_time="1-2 weeks full recovery",
                    success_rate=99.0,
                    references=["AAOMS Guidelines"]
                )
            }
        }
        
        # Get primary treatment
        primary = treatment_map.get(condition, {}).get(
            severity,
            TreatmentOption(
                name="Clinical Evaluation Required",
                category=TreatmentCategory.PREVENTIVE.value,
                description="Comprehensive clinical examination needed for treatment planning",
                indications=["All detected conditions"],
                contraindications=[],
                procedure_steps=["Schedule clinical appointment", "Complete examination", "Radiographic assessment"],
                estimated_cost_range={"min": 200, "max": 500, "currency": "AED"},
                recovery_time="N/A",
                success_rate=95.0,
                references=["General Clinical Practice"]
            )
        )
        
        # Generate alternatives
        alternatives = []
        if condition in treatment_map:
            for sev, treatment in treatment_map[condition].items():
                if sev != severity:
                    alternatives.append(treatment)
        
        return primary, alternatives[:2]
    
    def _generate_follow_ups(self, condition: str, severity: str) -> List[str]:
        """Generate follow-up recommendations."""
        follow_ups = [
            "Schedule follow-up appointment in 2 weeks for post-treatment evaluation",
            "Radiographic assessment at 6 months and 12 months",
            "Maintain excellent oral hygiene - brush twice daily, floss once daily"
        ]
        
        if severity in ["severe", "critical"]:
            follow_ups.insert(0, "URGENT: Schedule treatment within 1-2 days")
            follow_ups.append("Report any pain, swelling, or fever immediately")
        
        if condition == "Periapical Lesion":
            follow_ups.append("Complete antibiotic course if prescribed")
            follow_ups.append("Annual radiographic monitoring for healing")
        
        return follow_ups
    
    def _assess_prognosis(
        self,
        condition: str,
        severity: str,
        guidelines: List[Dict]
    ) -> str:
        """Assess treatment prognosis."""
        prognosis_map = {
            ("Caries", "mild"): "Excellent - 95% success with early intervention",
            ("Caries", "moderate"): "Very Good - 90-95% success at 5 years with proper restoration",
            ("Deep Caries", "severe"): "Good - 80-90% pulp preservation with conservative approach",
            ("Periapical Lesion", "critical"): "Good - 85-95% healing with proper endodontic treatment",
            ("Impacted", "moderate"): "Excellent - 99% success for routine surgical extraction",
        }
        
        return prognosis_map.get(
            (condition, severity),
            "Favorable with appropriate treatment and compliance"
        )


# Convenience functions
def get_treatment_recommendation(
    condition: str,
    severity: str = "moderate"
) -> Dict[str, Any]:
    """
    Quick function to get treatment recommendation.
    
    Args:
        condition: Dental condition
        severity: Severity level
        
    Returns:
        Treatment plan dictionary
    """
    rag = DentalGuidelinesRAG()
    plan = rag.generate_treatment_plan(condition, severity)
    return plan.to_dict()


if __name__ == "__main__":
    print("Dental RAG System - Demo")
    print("=" * 50)
    
    rag = DentalGuidelinesRAG()
    
    # Test retrieval
    print("\n1. Retrieving guidelines for 'Deep Caries':")
    guidelines = rag.retrieve_guidelines("Deep Caries", "severe")
    for g in guidelines:
        print(f"   - Relevance: {g['relevance_score']}")
        print(f"     {g['content'][:200]}...")
    
    # Test treatment plan generation
    print("\n2. Generating treatment plan:")
    plan = rag.generate_treatment_plan("Periapical Lesion", "critical")
    print(json.dumps(plan.to_dict(), indent=2, default=str))
